resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml
  OS::TripleO::Telemetry::Net::SoftwareConfig: /home/stack/templates/nic-configs/telemetry.yaml

parameter_defaults:
  # This sets 'external_network_bridge' in l3_agent.ini to an empty string
  # so that external networks act like provider bridge networks (they
  # will plug into br-int instead of br-ex)
  NeutronExternalNetworkBridge: "''"

  # Internal API used for private OpenStack Traffic
  InternalApiNetCidr: 10.10.14.0/24
  InternalApiAllocationPools: [{'start': '10.10.14.150', 'end': '10.10.14.200'}]
  InternalApiNetworkVlanID: 514



  # Tenant Network Traffic - will be used for VXLAN over VLAN
  TenantNetCidr: 10.10.15.0/24
  TenantAllocationPools: [{'start': '10.10.15.150', 'end': '10.10.15.200'}]
  TenantNetworkVlanID: 176


  # Storage network is not needed because the SAN Hitachi is provided with Fiber Channel

  # Public Storage Access - e.g. Nova/Glance <--> Ceph
  StorageNetCidr: 10.10.12.0/24
  StorageAllocationPools: [{'start': '10.10.12.150', 'end': '10.10.12.200'}]
  StorageNetworkVlanID: 400

  # Backup Network
  StorageMgmtNetCidr: 10.10.13.0/24
  StorageMgmtAllocationPools: [{'start': '10.10.13.150', 'end': '10.10.13.200'}]
  StorageMgmtNetworkVlanID: 513


  # External Networking Access - Public API Access
  ExternalNetCidr: 10.10.16.0/24
  # Leave room for floating IPs in the External allocation pool (if required)
  ExternalAllocationPools: [{'start': '10.10.16.150', 'end': '10.10.16.200'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.10.16.1


  # Add in configuration for the Control Plane
  ControlPlaneSubnetCidr: "24"
  ControlPlaneDefaultRoute: 10.10.11.1 
  EC2MetadataIp: 10.10.11.2
  DnsServers: ['10.10.11.1', '8.8.8.8']


  # Bonding options 
  # Mode = 1 active/passive
  # miimon= Specifies (in milliseconds) how often MII link monitoring occurs
  BondInterfaceOvsOptions: 'mode=1 miimon=150'

  # Set to empty string to enable multiple external networks or VLANs
  # NeutronExternalNetworkBridge: "''"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  # NeutronTunnelTypes: 'vxlan'
  #

  CloudName: openstack.example.com
  CloudNameInternal: overcloud.internalapi.example.com
  CloudNameCtlplane: overcloud.ctlplane.example.com
  CloudDomain: example.com
  
  ExtraConfig:
    neutron::dns_domain: example.com
    nova::network::neutron::dhcp_domain: example.com
  ServiceNetMap:
    NeutronTenantNetwork: tenant
    CeilometerApiNetwork: internal_api
    AodhApiNetwork: internal_api
    GnocchiApiNetwork: internal_api
    MongoDbNetwork: internal_api
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    GlanceApiNetwork: storage
    GlanceRegistryNetwork: internal_api
    KeystoneAdminApiNetwork: ctlplane # Admin connection for Undercloud
    KeystonePublicApiNetwork: internal_api
    NeutronApiNetwork: internal_api
    HeatApiNetwork: internal_api
    NovaApiNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    SwiftMgmtNetwork: storage_mgmt 
    SwiftProxyNetwork: storage
    SaharaApiNetwork: internal_api
    HorizonNetwork: internal_api
    MemcachedNetwork: internal_api
    RabbitMqNetwork: internal_api
    RedisNetwork: internal_api
    MysqlNetwork: internal_api
    CephClusterNetwork: storage_mgmt
    CephPublicNetwork: storage
    ControllerHostnameResolveNetwork: internal_api
    ComputeHostnameResolveNetwork: internal_api
    BlockStorageHostnameResolveNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    CephStorageHostnameResolveNetwork: storage
